/*
===============================================================================
Project : SQL Server → Amazon S3 using PySpark
Script  : 01_Create_Athletes_Big.sql

Author  : Claude Maxime Innocent

Purpose
-------
Create a large source table that simulates an enterprise production table
containing more than 10 million records.

This table will be used for:

• PySpark JDBC extraction
• Amazon S3 migration
• Parquet generation
• Spark performance testing
• Partitioned data lake storage
• Future AWS Glue and EMR projects

Design Notes
------------
athlete_sk
    Surrogate key generated by SQL Server.
    Used as Spark's partitionColumn during JDBC extraction.

athlete_hash_key
    SHA-256 hash used as a deterministic business key.
    Useful for:
        - duplicate detection
        - change detection
        - cross-system comparisons

athlete_id
    Original business key coming from the source system.

batch_id
    Represents a fictional ETL batch.

source_system
    Indicates where the data originated.

load_timestamp
    Simulates the exact time data entered the data lake.

load_date/year/month/day
    Used later by Spark to create partitioned folders in S3.

Example S3 layout:

s3://athletes-big/raw/
    load_year=2024/
        load_month=01/
            load_day=01/

===============================================================================
*/

USE AdventureWorksDW2014;
GO

-- Remove the table if it already exists.
DROP TABLE IF EXISTS dbo.Athletes_Big;
GO

-- Create the enterprise-sized source table.
CREATE TABLE dbo.Athletes_Big
(
    --------------------------------------------------------------------------
    -- Surrogate Key
    --------------------------------------------------------------------------
    athlete_sk BIGINT IDENTITY(1,1) NOT NULL,

    --------------------------------------------------------------------------
    -- Business Hash Key
    --------------------------------------------------------------------------
    athlete_hash_key CHAR(64) NOT NULL,

    --------------------------------------------------------------------------
    -- Original source columns
    --------------------------------------------------------------------------
    athlete_id INT NOT NULL,
    name NVARCHAR(200),
    born_date DATE,
    born_city NVARCHAR(100),
    born_region NVARCHAR(100),
    born_country CHAR(50),
    NOC NVARCHAR(100),
    height_cm DECIMAL(5,2),
    weight_kg DECIMAL(5,2),
    died_date DATE,

    --------------------------------------------------------------------------
    -- ETL metadata
    --------------------------------------------------------------------------
    batch_id INT NOT NULL,
    source_system VARCHAR(30) NOT NULL,

    --------------------------------------------------------------------------
    -- Data Lake partition columns
    --------------------------------------------------------------------------
    load_timestamp DATETIME2 NOT NULL,
    load_date DATE NOT NULL,
    load_year INT NOT NULL,
    load_month INT NOT NULL,
    load_day INT NOT NULL,

    --------------------------------------------------------------------------
    -- Constraints
    --------------------------------------------------------------------------
    CONSTRAINT PK_Athletes_Big
        PRIMARY KEY CLUSTERED (athlete_sk),

    CONSTRAINT UQ_Athletes_Big_Hash
        UNIQUE (athlete_hash_key)
);
GO